var mongoose = require('mongoose');

//Define a schema 
var Schema = mongoose.Schema;

var SubscriptionSchema = new Schema({
	//_id (id) will be generated by default (type ObjectId)
	user: { 
		type: Schema.Types.ObjectId, 
		ref: 'TwitterUser',
		required: true 
	}

});

// Compile model from schema
var SubscriptionModel = mongoose.model('Subscription', SubscriptionSchema);


module.exports = SubscriptionModel;