var mongoose = require('mongoose');

//Define a schema 
var Schema = mongoose.Schema;

var SubscriptionSchema = new Schema({
	//_id (id) will be generated by default (type ObjectId)
	// user: { 
	// 	type: Schema.Types.ObjectId, 
	// 	ref: 'TwitterUser',
	// 	required: true 
	// }
	user: {
		id_str: {
			type: String,
			unique: true,
			required: true
		},
		name: String,
		screen_name: String,
		location: String,
		url: String,
		description: String,
		protected: Boolean,
		verified: Boolean,
		created_at: String,
		profile_banner_url: String,
		profile_image_url: String,
		profile_image_url_https: String
	}

});

// Compile model from schema
var SubscriptionModel = mongoose.model('Subscription', SubscriptionSchema);


module.exports = SubscriptionModel;